In [5]:
from sklearn.datasets import load_diabetes
import numpy as np
from sklearn.metrics import r2_score

In [7]:
X, y = load_diabetes (return_X_y= True)

In [33]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,y , test_size =0.2, random_state = 2)

In [35]:
# using sklearn


In [37]:
from sklearn.linear_model import SGDRegressor

In [39]:
reg = SGDRegressor(penalty='l2',max_iter=500,eta0=0.1,learning_rate='constant',alpha=0.001)

In [41]:
reg.fit(X_train, Y_train)

SGDRegressor(alpha=0.001, eta0=0.1, learning_rate='constant', max_iter=500)

In [43]:
y_pred = reg.predict(X_test)

In [45]:
r2_score(Y_test, y_pred)

0.3543338314014335

In [47]:
reg.coef_


array([  34.41673744, -117.51243089,  395.03600867,  271.2427123 ,
        -12.22204029,  -69.54572679, -168.9927093 ,  103.51094043,
        362.44780956,  101.6654504 ])

In [49]:
reg.intercept_

array([130.18855913])

In [53]:
from sklearn.linear_model import Ridge

In [55]:
reg = Ridge(alpha=0.001, max_iter=500,solver='sparse_cg')

In [57]:
reg.fit(X_train, Y_train)

Ridge(alpha=0.001, max_iter=500, solver='sparse_cg')

In [61]:
y_pred = reg.predict(X_test)

In [63]:
r2_score(Y_test, y_pred)

0.4408617108948182

In [65]:
reg.coef_

array([  -8.76148558, -204.31340331,  518.38061048,  339.96792773,
       -787.70050808,  475.28218344,  106.79525123,  114.62926765,
        819.74572525,   52.87335148])

In [67]:
reg.intercept_

151.88534079191118

In [116]:
class MeraRidgeReg:
    def __init__(self, learning_rate, epochs , alpha):
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.alpha = alpha
        self.m =None
        self.b = None
    def fit(self,X_train, Y_train):
        self.coef_ = np.ones(X_train.shape[1])
        self.intercept_= 0
        theta = np.insert(self.coef_, 0, self.intercept_)
        X_train = np.insert(X_train, 0, 1, axis=1)
        for i in range (self.epochs):
            theta_dr = np.dot(X_train.T ,X_train).dot(theta ) -np.dot(X_train.T, Y_train) + self.alpha*theta 
            theta = theta - self.learning_rate*theta_dr
        self.coef_ = theta[1:]
        self.intercept_ = theta[0]
    def predict(self,X_test):
        
        return np.dot(X_test,self.coef_) + self.intercept_
            
            


        

    

In [118]:
reg = MeraRidgeReg(epochs=500,alpha=0.001,learning_rate=0.005)

In [122]:
reg.fit(X_train,Y_train)

y_pred = reg.predict(X_test)
print("R2 score",r2_score(Y_test,y_pred))
print(reg.coef_)
print(reg.intercept_)

R2 score 0.45395431712097367
[  19.50919039 -162.92602513  478.95477998  317.86376108  -34.07709121
 -108.63608801 -193.66871805  106.94769192  437.10746813  103.57606041]
152.03121813717044
